### ISSUE TITLE
Enhancement:  Panic Handling For Non_Standard PE Files

### ISSUE THREAD

**Issue by dfirence** [dfirence/pe-compass#10]
When Non PE32 or PE32+ files are parsed, the section headers are absent from these types of PE files.  Upon detecting the unconventional structure, `pe-compass` is panicking correctly and custom message is triggering correctly

```
Unable to Convert SECTION_NAME From UTF-8 Bytes
```

Need now a non-exception handling.

```text
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : compobj.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : ole2.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : ole2disp.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : ole2nls.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : storage.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : typelib.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : compobj.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : ole2.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : ole2disp.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : ole2nls.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : storage.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : typelib.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : compobj.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : ole2.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : ole2disp.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : ole2nls.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : storage.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : typelib.dll: FromUtf8Error { bytes: [192, 136, 134, 238, 254, 136, 134, 220], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src\libcore\result.rs:1188:5
```

<br />

These files are inspected as

<br />

![image](https://user-images.githubusercontent.com/11415591/79022109-362e7780-7b4b-11ea-86aa-f8f73c8660cb.png)

<br />

Notice Unconventional DOS Header and absence PE Magic

<br /> 

![image](https://user-images.githubusercontent.com/11415591/79022219-6f66e780-7b4b-11ea-93c5-95642da7d7c9.png)

**Comment by dfirence** [comment]
New condition to validate the PE_SIGNATURE for the abnormal ...NE... Bytes is implemented.

Now there's no need to panic with these types of files.  I am leaving the `panics` in place to detect more abnormal file types that demonstrate these types of missing spec attributes.

The user will see an informational message printed to stdout denoting the `...NE...` signature was observed and that it is not supported.

```powershell
PS C:\>pe-compass.exe  inspect -f compobj.dll
```

```
(?) Info:       Unsupported PE File Type: Has `...NE...` signature
                Only PE32 or PE32+ Files Are Supported
```
