### ISSUE TITLE
Errors processing certain samples

### ISSUE THREAD

**Issue by seifreed** [dfirence/pe-compass#15]
Running PE Compass, I'm getting some errors for certain samples:

```
thread 'main' panicked at 'Unable to Serialize First Name From Exports : 3b7585f4ba0a931be938fb576af2dafe89fdd4cc65f777febd1a5f47d9c5bc54: BadOffset(3160823346)', src/utils/args/../../modules/pe_parser.rs:938:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unable to Convert SECTION_NAME From UTF-8 Bytes : 3c95f5b3e07449bb05c2cacafbb12ca69cecf2496328b1c700ec1073ad52e99a: FromUtf8Error { bytes: [46, 116, 101, 120, 116, 147], error: Utf8Error { valid_up_to: 5, error_len: Some(1) } }', src/utils/args/../../modules/pe_parser.rs:456:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unable to Serialize THUNK_DATA32 From IMAGE_DESCRIPTOR : 4e74a7f4f61bba1e1f4cfc2c90d1455ee787f9d6eab910c5828c55eb9b1f8b05: BadOffset(805322668)', src/utils/args/../../modules/pe_parser.rs:777:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unable to Serialize Function Name from THUNK_DATA64 : 5f97741d6beab5fb38e7821c36e7e2662fc3dfc7d01f1248d844599e0bbd730d: BadOffset(50231388)', src/utils/args/../../modules/pe_parser.rs:888:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unable to Serialize DLL_NAME from IMPORT_DESCRIPTOR : 5ff87334bd85918f285b491b9decf5c9d43f9e225a4e7d4689024bf055471d45: BadOffset(4278288)', src/utils/args/../../modules/pe_parser.rs:738:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unable to Serialize DLL_NAME from IMPORT_DESCRIPTOR : 94ef8d0fc281b585939e24e25fdd27ce4d69b275746b5d97fb973308453fe193: BadOffset(472757)', src/utils/args/../../modules/pe_parser.rs:738:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unable to Serialize Function Name from THUNK_DATA32 : a67855dbd18652e99f13d29045b09391382bb8c817cda1e498cd01eb4a7bdf2c: BadOffset(1917185826)', src/utils/args/../../modules/pe_parser.rs:842:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
pe-compass(72518,0x10519bdc0) malloc: *** error for object 0x7fead180a000: pointer being freed was not allocated
pe-compass(72518,0x10519bdc0) malloc: *** set a breakpoint in malloc_error_break to debug
thread 'main' panicked at 'Unable to Serialize IMPORT_DESCRIPTOR From Section Pointer : b541a9f64fe12c31fff460ab0deef392a8441eeb102805ed578effc6e6eaed96: BadOffset(315689)', src/utils/args/../../modules/pe_parser.rs:581:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unable to Serialize First Name From Exports : ceb35555e36f31727e351c0b68fdbcb11d0d3d75051be0feb69fd97cabbd528e: BadOffset(1907826974)', src/utils/args/../../modules/pe_parser.rs:938:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unable to Serialize First Name From Exports : da2eecf561bfca7e695dbaf97ef468b8a32713388a215a5284d95c757047d7df: BadOffset(451294492)', src/utils/args/../../modules/pe_parser.rs:938:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unable to serialize IMAGE_EXPORT_DIRECTORY : dafb65efb81ae6abdfbea11c40fcdca2b2606069f9578273b408a4bd1c6f6b1b: BadOffset(172512)', src/utils/args/../../modules/pe_parser.rs:923:48
```

**Comment by dfirence** [comment]
Hi Seifreed

Are these samples Packed? Either with UPX or encrypted in some fashion?

Reference this please:

https://github.com/dfirence/pe-compass/issues/10

That was the last testing case where I needed to add to PE_COMPASS support for non-standard PE Files.

The errors you are seeing are telling us the Key Sections and IAT structs are unrecognizable. Therefore leading me to ask if these are packed or encrypted. 

At this moment, PE_COMPASS has no support for parsing packed files. 

If they are not packed or encrypted, I need the sample and debug this. 

Thanks for submitting the issue

**Comment by dfirence** [comment]
can u confirm the samples are packed?

**Comment by dfirence** [comment]
No response from requester, the hashes in the examples were referenced with sandboxes and the UPX section names indicate these files are packed. 

As mentioned in the README, PE-Compass currently does not parse packed files.
